/**
 * SSE service for AI-generated ancestor stories.
 * Uses XMLHttpRequest for streaming in React Native (fetch doesn't support ReadableStream).
 * Called from OB07_Promise on mount.
 */

import {BACKEND_URL} from '../constants/onboarding';
import {createSSEStream} from './sseStreamService';

interface StreamParams {
  firstName: string;
  regions: string[];
  motivation: string;
  visitFrequency: string;
  goal: string;
  onChunk: (text: string) => void;
  onDone: (monument: string) => void;
  onError: () => void;
}

export function streamAncestorStory({
  firstName,
  regions,
  motivation,
  visitFrequency,
  goal,
  onChunk,
  onDone,
  onError,
}: StreamParams): () => void {
  let hasErrored = false;
  let hasDone = false;

  const safeOnError = () => {
    if (hasErrored || hasDone) {
      return;
    }
    hasErrored = true;
    console.log('[AncestorStory] Using fallback story (API error/unavailable)');
    onError();
  };

  const handleMessage = (payload: Record<string, unknown>) => {
    const message = payload as {
      type?: string;
      text?: string;
      monument?: string;
    };

    if (message.type === 'chunk' && typeof message.text === 'string') {
      onChunk(message.text);
      return;
    }

    if (message.type === 'done') {
      hasDone = true;
      console.log('[AncestorStory] Story generated by Gemini ✓ monument:', message.monument);
      onDone(message.monument ?? 'Unknown Monument');
      return;
    }

    if (message.type === 'error') {
      safeOnError();
    }
  };

  const abort = createSSEStream({
    url: `${BACKEND_URL}/api/onboarding/ancestor-story`,
    body: {firstName, regions, motivation, visitFrequency, goal},
    timeout: 30000,
    onMessage: handleMessage,
    onError: safeOnError,
  });

  return () => {
    abort();
  };
}
