/**
 * SSE service for AI-generated ancestor stories.
 * Uses XMLHttpRequest for streaming in React Native (fetch doesn't support ReadableStream).
 * Called from OB07_Promise on mount.
 */

import {BACKEND_URL} from '../constants/onboarding';
import {streamGeminiText} from '../shared/api/gemini.client';
import {getFallbackStory} from './fallbackStories';
import {createSSEStream} from './sseStreamService';

interface StreamParams {
  firstName: string;
  regions: string[];
  motivation: string;
  visitFrequency: string;
  goal: string;
  onChunk: (text: string) => void;
  onDone: (monument: string) => void;
  onError: () => void;
}

function buildAncestorPrompt({
  firstName,
  regions,
  motivation,
  visitFrequency,
  goal,
  monument,
}: {
  firstName: string;
  regions: string[];
  motivation: string;
  visitFrequency: string;
  goal: string;
  monument: string;
}): string {
  const selectedRegions = regions.length > 0 ? regions.join(', ') : 'South Asia';
  const cleanMotivation = motivation.trim().length > 0 ? motivation : 'heritage connection';
  const cleanVisitFrequency =
    visitFrequency.trim().length > 0 ? visitFrequency : 'occasional visits';

  return [
    `Write one immersive ancestor story for ${firstName}.`,
    `Anchor the story around ${monument}.`,
    `Preferred lineage regions: ${selectedRegions}.`,
    `Motivation: ${cleanMotivation}.`,
    `Visit frequency: ${cleanVisitFrequency}.`,
    `Goal cadence: ${goal}.`,
    'Constraints:',
    '- 170 to 230 words.',
    '- Use second-person voice and emotionally grounded historical tone.',
    '- Keep the monument and era plausible.',
    '- Return plain text only, no title, no markdown, no bullet points.',
  ].join('\n');
}

export function streamAncestorStory({
  firstName,
  regions,
  motivation,
  visitFrequency,
  goal,
  onChunk,
  onDone,
  onError,
}: StreamParams): () => void {
  const safeFirstName = firstName.trim().length > 0 ? firstName : 'Explorer';
  const primaryRegion = regions[0] ?? 'South Asia';
  const fallbackMonument = getFallbackStory(primaryRegion, safeFirstName).monument;

  let hasErrored = false;
  let hasDone = false;
  let hasReceivedChunk = false;
  let hasStartedDirectGemini = false;
  let activeAbort: (() => void) | null = null;

  const safeOnError = () => {
    if (hasErrored || hasDone) {
      return;
    }
    hasErrored = true;
    console.log('[AncestorStory] Using fallback story (API error/unavailable)');
    onError();
  };

  const safeOnDone = (monument: string) => {
    if (hasErrored || hasDone) {
      return;
    }

    hasDone = true;
    onDone(monument);
  };

  const handleChunk = (text: string) => {
    if (hasErrored || hasDone || text.length === 0) {
      return;
    }

    hasReceivedChunk = true;
    onChunk(text);
  };

  const startDirectGeminiFallback = () => {
    if (hasStartedDirectGemini || hasErrored || hasDone) {
      return;
    }

    hasStartedDirectGemini = true;
    console.log('[AncestorStory] Backend stream failed, retrying with direct Gemini');

    activeAbort = streamGeminiText({
      prompt: buildAncestorPrompt({
        firstName: safeFirstName,
        regions,
        motivation,
        visitFrequency,
        goal,
        monument: fallbackMonument,
      }),
      systemInstruction:
        'You are a careful heritage storyteller. Keep output vivid, respectful, and plain text.',
      temperature: 0.8,
      maxOutputTokens: 420,
      timeout: 30000,
      onChunk: handleChunk,
      onDone: () => {
        safeOnDone(fallbackMonument);
      },
      onError: safeOnError,
    });
  };

  const handleBackendFailure = () => {
    if (hasErrored || hasDone) {
      return;
    }

    // Avoid blending two partially-generated narratives.
    if (hasReceivedChunk) {
      safeOnError();
      return;
    }

    startDirectGeminiFallback();
  };

  const handleBackendMessage = (payload: Record<string, unknown>) => {
    const message = payload as {
      type?: string;
      text?: string;
      monument?: string;
    };

    if (message.type === 'chunk' && typeof message.text === 'string') {
      handleChunk(message.text);
      return;
    }

    if (message.type === 'done') {
      const monument =
        typeof message.monument === 'string' && message.monument.length > 0
          ? message.monument
          : fallbackMonument;
      console.log('[AncestorStory] Story generated by backend Gemini ✓ monument:', monument);
      safeOnDone(monument);
      return;
    }

    if (message.type === 'error') {
      handleBackendFailure();
    }
  };

  activeAbort = createSSEStream({
    url: `${BACKEND_URL}/api/onboarding/ancestor-story`,
    body: {firstName, regions, motivation, visitFrequency, goal},
    timeout: 30000,
    onMessage: handleBackendMessage,
    onError: handleBackendFailure,
  });

  return () => {
    activeAbort?.();
  };
}
