/**
 * Universal "museum mode" client.
 *
 * Posts a single camera frame to the backend vision endpoint and relays the
 * SSE response. The backend does the cost-controlled two-tier work:
 *   cheap identify (per tap) → normalize label → Redis/DB cache
 *     → hit:  replay cached narration (no Gemini narration call)
 *     → miss: stream a hedged narration (text-only) + persist
 *
 * From the client's side this is ONE request. The expensive narration is
 * generated by Gemini at most once per distinct object, ever — every later
 * visitor who points at the same object is served from the shared cache.
 *
 * Frames:
 *   { type: 'object', label }          → onObject(label)   (card title, arrives first)
 *   { type: 'chunk',  text }           → onChunk(text)     (typewriter narration)
 *   { type: 'done',   cached, source } → onDone({cached, source})
 *   { type: 'error',  message }        → onError(message)
 */

import { BACKEND_URL } from '../constants/onboarding';
import { createSSEStream } from './sseStreamService';
import { getValidAccessToken } from '../utils/api/auth';

export interface MuseumNarrationHandlers {
  imageUri: string;
  /** Optional venue context (nearest place name) to bias toward the specific artifact. */
  venue?: string | null;
  /** Optional GPS, accepted by the backend for logging/future use. */
  lat?: number | null;
  lng?: number | null;
  /** Narration language (en/hi/bn). Defaults to English server-side if omitted. */
  lang?: 'en' | 'hi' | 'bn';
  /**
   * Active venue slug (e.g. 'indian-museum') when inside a seeded zone. Scopes
   * grounded matching to that venue's curated objects; absent → fallback only.
   */
  venueSlug?: string | null;
  onObject: (label: string) => void;
  onChunk: (text: string) => void;
  onDone: (info: { cached: boolean; source?: string }) => void;
  onError: (message?: string) => void;
  /**
   * Per-site free-scan paywall: the visitor has spent their free scans at this
   * seeded venue. Terminal — no narration follows. Show the site paywall.
   */
  onPaywall?: (info: { siteId: string; used: number; limit: number }) => void;
  /** Remaining per-site free scans after a successful serve (for the counter). */
  onScanMeta?: (info: { siteId: string; remaining: number }) => void;
}

type RNFile = { uri: string; type: string; name: string };

/**
 * Kicks off a museum-mode identification + narration stream for a captured
 * frame. Returns an abort function — call it on unmount or re-tap.
 */
export function streamMuseumNarration({
  imageUri,
  venue,
  lat,
  lng,
  lang,
  venueSlug,
  onObject,
  onChunk,
  onDone,
  onError,
  onPaywall,
  onScanMeta,
}: MuseumNarrationHandlers): () => void {
  let settled = false;
  let aborted = false;
  let innerAbort: (() => void) | null = null;

  const safeError = (message?: string) => {
    if (settled || aborted) return;
    settled = true;
    onError(message);
  };

  const handleMessage = (payload: Record<string, unknown>) => {
    const msg = payload as {
      type?: string;
      label?: string;
      text?: string;
      cached?: boolean;
      source?: string;
      message?: string;
      site_id?: string;
      used?: number;
      limit?: number;
      remaining?: number;
    };

    if (msg.type === 'object' && typeof msg.label === 'string') {
      onObject(msg.label);
      return;
    }
    if (msg.type === 'chunk' && typeof msg.text === 'string') {
      onChunk(msg.text);
      return;
    }
    if (msg.type === 'paywall') {
      // Terminal: free scans spent at this venue. Mark settled so the stream
      // closing without a 'done' frame doesn't surface as an error.
      if (settled) return;
      settled = true;
      onPaywall?.({
        siteId: typeof msg.site_id === 'string' ? msg.site_id : '',
        used: typeof msg.used === 'number' ? msg.used : 0,
        limit: typeof msg.limit === 'number' ? msg.limit : 0,
      });
      return;
    }
    if (msg.type === 'scan_meta') {
      onScanMeta?.({
        siteId: typeof msg.site_id === 'string' ? msg.site_id : '',
        remaining: typeof msg.remaining === 'number' ? msg.remaining : 0,
      });
      return;
    }
    if (msg.type === 'done') {
      if (settled) return;
      settled = true;
      onDone({ cached: msg.cached === true, source: msg.source });
      return;
    }
    if (msg.type === 'error') {
      safeError(typeof msg.message === 'string' ? msg.message : undefined);
    }
  };

  // Auth token is fetched async; the endpoint is behind middleware.Auth.
  void (async () => {
    const token = await getValidAccessToken();
    if (aborted) return;

    const formData = new FormData();
    formData.append('image', {
      uri: imageUri,
      type: 'image/jpeg',
      name: 'museum-frame.jpg',
    } as unknown as RNFile);
    if (venue && venue.trim().length > 0) {
      formData.append('venue', venue.trim());
    }
    if (typeof lat === 'number' && Number.isFinite(lat)) {
      formData.append('lat', String(lat));
    }
    if (typeof lng === 'number' && Number.isFinite(lng)) {
      formData.append('lng', String(lng));
    }
    if (lang) {
      formData.append('lang', lang);
    }
    if (venueSlug && venueSlug.trim().length > 0) {
      formData.append('venueSlug', venueSlug.trim());
    }

    innerAbort = createSSEStream({
      url: `${BACKEND_URL}/api/v1/vision/identify`,
      body: formData,
      timeout: 35000,
      headers: token ? { Authorization: `Bearer ${token}` } : undefined,
      onMessage: handleMessage,
      onError: () => safeError(),
    });
  })();

  return () => {
    aborted = true;
    innerAbort?.();
  };
}
