/**
 * PromptStep — step 2 of the journey. Off the lawn, before the pillars: put the
 * earphones in, and the ONE place the journey says where its words come from.
 *
 * The disclaimer is deliberately here and nowhere else (hard rules 2 and 3):
 * the history is from the ASI's archives and published books, the storytelling
 * is generated by AI, and the figure is a depiction. No card, placard or later
 * step repeats any of it.
 *
 * While the visitor reads, the guide's audio and card video keep saving to the
 * device (started on the lawn). Progress is shown in words; nothing blocks on
 * it — anything not saved by the time it is needed simply streams.
 */
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTranslation } from 'react-i18next';
import { Headphones, TriangleAlert } from 'lucide-react-native';

import { useNetwork } from '../../../context/NetworkContext';
import { COLORS } from '../../../core/constants/theme';
import type { PrefetchSummary } from '../../../services/mediaCache';
import {
  JOURNEY_GOLD,
  JOURNEY_INK,
  PrimaryButton,
  journeyStyles,
} from './JourneyUi';

interface Props {
  /** Running pre-cache tally; null until the first file settles. */
  prefetch: PrefetchSummary | null;
  /** True once the pre-cache run has finished (with or without failures). */
  prefetchDone: boolean;
  onContinue: () => void;
}

const PromptStep: React.FC<Props> = ({ prefetch, prefetchDone, onContinue }) => {
  const { t } = useTranslation();
  const { isConnected } = useNetwork();

  let cachingLine: string;
  if (!isConnected) {
    cachingLine = t('journey.prepare.caching.offline');
  } else if (prefetchDone) {
    cachingLine =
      prefetch && prefetch.failed > 0
        ? t('journey.prepare.caching.partial')
        : t('journey.prepare.caching.ready');
  } else if (prefetch && prefetch.total > 0) {
    cachingLine = t('journey.prepare.caching.progress', {
      done: prefetch.cached + prefetch.failed,
      total: prefetch.total,
    });
  } else {
    cachingLine = t('journey.prepare.caching.waiting');
  }

  return (
    <SafeAreaView style={journeyStyles.root} edges={['top', 'bottom']}>
      <ScrollView
        style={journeyStyles.page}
        contentContainerStyle={journeyStyles.pageContent}
        showsVerticalScrollIndicator={false}>
        <Text style={journeyStyles.eyebrow}>{t('journey.prepare.eyebrow')}</Text>
        <Text style={journeyStyles.title}>{t('journey.prepare.title')}</Text>

        {/* EARPHONES ARE ENCOURAGED, NEVER REQUIRED.
            Nothing here gates on them and nothing checks the audio route — the
            phone speaker is a perfectly good way to hear the guide. What the copy
            now adds is the TIMING, and that is not a nicety: useAudioCompletion
            documents that a headphone or Bluetooth route change AT THE MOMENT
            playback starts can have Android deny audio focus, after which
            react-native-video never retries and never emits an event. That is the
            frozen-lawn bug. Asking people to connect first costs nothing and
            removes the most likely cause of a silent welcome. */}
        <View style={styles.row}>
          <Headphones size={22} color={JOURNEY_GOLD} />
          <Text style={[journeyStyles.bodyStrong, styles.rowText]}>
            {t('journey.prepare.earphones')}
          </Text>
        </View>

        {/* SAY THAT AR CAN FAIL, BEFORE THE CAMERA OPENS.
            The journey plants a life-size figure on the floor and starts a
            35-second narration, and none of that is guaranteed: tracking is lost
            in a dark room, on a plain wall, when the phone is swung fast, or when
            it throttles in the sun. Promising a seamless experience and then
            delivering an empty camera feed is what produced the "he's absent /
            it didn't place" reports. One honest sentence here changes a failure
            from a betrayal into an expected, recoverable event — and the live
            banner (ArSessionBanner) then names whichever cause actually hit. */}
        <View style={styles.row}>
          <TriangleAlert size={22} color={JOURNEY_GOLD} />
          <Text style={[journeyStyles.body, styles.rowText]}>
            {t('journey.prepare.arCaution')}
          </Text>
        </View>

        <View style={styles.card}>
          <Text style={journeyStyles.eyebrow}>{t('journey.prepare.disclaimerTitle')}</Text>
          <Text style={journeyStyles.body}>{t('journey.prepare.disclaimerHistory')}</Text>
          <Text style={journeyStyles.body}>{t('journey.prepare.disclaimerStorytelling')}</Text>
          <Text style={journeyStyles.body}>{t('journey.prepare.disclaimerFigure')}</Text>
        </View>

        <View style={styles.caching}>
          <Text style={journeyStyles.caption}>{t('journey.prepare.caching.title')}</Text>
          <Text style={journeyStyles.bodyStrong}>{cachingLine}</Text>
        </View>
      </ScrollView>

      {/* THE WAY FORWARD IS PINNED, NOT SCROLLED TO.
          This button used to be the last child INSIDE the ScrollView, below a
          four-paragraph disclaimer card and the caching block. On a phone it sat
          under the fold, so the last thing a visitor saw was "Preparing your
          guide / Getting ready…" — and they reported the journey as stuck at
          exactly that line. Nothing was broken; the only control was off-screen.
          Pinning it outside the scroll area means the step can never again LOOK
          like it has stalled while it is simply waiting to be read. */}
      <View style={styles.footer}>
        <PrimaryButton
          label={t('journey.prepare.acknowledge')}
          onPress={onContinue}
        />
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginTop: 4 },
  rowText: { flex: 1 },
  card: {
    backgroundColor: COLORS.bgWarm,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.borderFocus,
    padding: 18,
    gap: 10,
    marginTop: 6,
  },
  caching: { gap: 4, marginTop: 4 },
  footer: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderFocus,
    backgroundColor: JOURNEY_INK,
  },
});

export default PromptStep;
