/**
 * Tipu Sultan's Summer Palace magic window - the authored standing positions.
 *
 * GENERATED by heritage_assets/tipu-summer-palace-bengaluru/tools/
 * emit_palace_ts.py from output/palace_viewpoints.json, which
 * build_palace_magicwindow.py writes alongside the GLB itself. Do not hand-edit:
 * change the research or the builder and re-emit, or the model and the camera
 * positions drift apart.
 *
 * COORDINATE FRAME - the building's own, from palace-dimensions.json, and NOT
 * georeferenced (a magic window needs no georeference).
 *   origin  centre of the principal (ESE) facade, at plinth-floor level
 *   +X      along the facade toward the NNE end   (true bearing 16.8 deg)
 *   +Y      into the building                     (true bearing 286.8 deg)
 *   +Z      up; plinth floor z = 0, external ground z = -0.70
 *
 * `position` is the CAMERA, eye height already added - the research stores a
 * floor point and a separate 1.6 m eye height, and the emitter adds them.
 * `headingDeg` is frame-relative with 0 = +Y, converted from the research's
 * true bearings by the emitter. Both conversions happen once, in the emitter.
 *
 * PRODUCT RULE: gyroscope look-around plus tap-to-jump. No camera, no tracking,
 * no permissions, no drift. The ARCore 6DoF walking tier is deliberately not
 * shipped here - of these ten positions only ONE pair falls inside the ~8 m
 * drift budget, so walking would buy a single real walk in exchange for a
 * permission prompt and a device gate.
 */

import type {MagicWindowViewpoint} from './viewpoints';

/**
 * The model id resolved through `src/services/glbSource.ts`.
 *
 * v7 = v6 with the glTF SPEC ERRORS fixed. `@gltf-transform/cli validate` found
 * 5,427 of them in the shipped v6, all from two causes, neither of which any
 * renderer had complained about:
 *   - COLOR_0 is a NORMALIZED unsigned-byte accessor, and its min/max must be
 *     stated in RAW component space (integers 0..255), not in the [0,1] space a
 *     reader sees after normalising. v6 wrote the floats: 4,011
 *     ARRAY_TYPE_MISMATCH plus 708 ACCESSOR_MAX_MISMATCH and 708
 *     ACCESSOR_ELEMENT_OUT_OF_MAX_BOUND, because "declared max 1, actual 255".
 *   - one baseColorFactor at 1.0461, from an srgb(1.02, ...) warm tint. The
 *     factor is spec-limited to [0,1]; srgb() now refuses out-of-range input
 *     rather than clamping, because clamping one channel shifts the HUE.
 * Filament ignores both, which is exactly why they shipped unseen.
 *
 * v2 = the palace with NO sky dome in the model. A 200 m dome around a 31 m
 * building made the GLB's bounding box 400 x 200 x 400 m, and on device that hid
 * the building entirely — bisected with three diagnostic GLBs while Blender, at
 * the camera transform read off the device's own telemetry, rendered the
 * interior correctly. The sky now comes from Filament, per scene.
 */
export const PALACE_MODEL_ID = 'tipu_summer_palace_magicwindow_v9';

/** The site this scene belongs to. */
export const PALACE_SLUG = 'tipu-summer-palace-bengaluru';

/**
 * True-scale span of the whole scene, in metres. EMITTED FROM THE BUILD, never
 * typed by hand: hand-maintaining it is exactly how it went stale the moment the
 * sky dome came out of the model and fired a false scale warning. Guards against
 * `scaleToUnits` normalisation shipping a doll's house.
 */
export const PALACE_SCENE_SPAN_M = 140.0;

/** The building itself: 31.35 m along the facade by 22.50 m deep. */
export const PALACE_FACADE_M = 31.35;
export const PALACE_DEPTH_M = 22.50;

/**
 * The palace footprint, for the on-screen position indicator.
 *
 * EMITTED FROM THE BUILD, never typed: every number is the one the geometry
 * was generated from, so the plan the visitor reads cannot drift from the
 * building they are standing in. Metres, in the building frame - +X along the
 * facade toward the NNE end, +Y into the building, origin at the centre of the
 * principal (ESE) facade.
 */
export const PALACE_PLAN = {
  "x_min": -20.375,
  "x_max": 10.975,
  "y_min": 0.0,
  "y_max": 22.5,
  "colonnade_x": [
    -9.375,
    9.375
  ],
  "end_block_x": [
    -20.375,
    -9.375
  ],
  "end_pier_x": [
    9.375,
    10.975
  ],
  "pillar_x": [
    -9.375,
    -5.625,
    -1.875,
    1.875,
    5.625,
    9.375
  ],
  "pillar_y": [
    0.0,
    3.75,
    7.5,
    11.25,
    15.0,
    18.75,
    22.5
  ],
  "wells": [
    {
      "x": [
        -5.625,
        5.625
      ],
      "y": [
        0.0,
        3.75
      ]
    },
    {
      "x": [
        -5.625,
        5.625
      ],
      "y": [
        18.75,
        22.5
      ]
    }
  ],
  "note": "building frame, metres. +X along the facade toward the NNE end, +Y into the building. Origin is the centre of the principal (ESE) facade."
} as const;

/**
 * Image credits, a LICENCE OBLIGATION.
 *
 * The painted field ships as a photograph of the actual wall under
 * CC BY 2.0, which requires attribution. Emitted from the build out of
 * research/photos/manifest.json for the photographs actually consumed by a
 * shipped texture, so the credit cannot drift from what is in the GLB.
 */
export const TEXTURE_CREDITS = [
  {
    "used_for": "the surviving painted wall, first-floor interior",
    "author": "Mike Prince from Bangalore, India",
    "licence": "CC BY 2.0",
    "licence_url": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tipu_Sultan%27s_Summer_Palace_(16414465309).jpg"
  }
] as const;

export const PALACE_VIEWPOINTS: MagicWindowViewpoint[] = [
  {
    id: 'P2',
    title: 'Down the arcade',
    position: [7.500, 1.900, 1.600],
    headingDeg: 270.00,
    pitchDeg: 0.00,
    fovDeg: 62.0,
    nearM: 0.35,
    farM: 150.0,
    facing: 'south-south-west',
    stopKey: 'the_pillars',
    caption:
      'The hero view: 18.7 m of receding cusped arcade. The same view ' +
      'Robert Home engraved in 1794.',
  },
  {
    id: 'P5',
    title: 'Durbar hall',
    position: [0.000, 9.000, 4.200],
    headingDeg: 0.00,
    pitchDeg: 0.00,
    fovDeg: 62.0,
    nearM: 0.35,
    farM: 150.0,
    facing: 'west-north-west',
    stopKey: 'the_lost_colour',
    caption:
      'The court. Red grounds, gilded arcade, galleries on both ' +
      'sides.',
  },
  {
    id: 'P1',
    title: 'Centre bay',
    position: [0.000, 1.900, 1.600],
    headingDeg: 0.00,
    pitchDeg: 0.00,
    fovDeg: 62.0,
    nearM: 0.35,
    farM: 150.0,
    facing: 'west-north-west',
    stopKey: 'into_the_shade',
    caption:
      'First step into the shade. The scale change from lawn to ' +
      'colonnade is the moment the reconstruction earns belief.',
  },
  {
    id: 'P6',
    title: 'Looking up',
    position: [0.000, 9.000, 4.200],
    headingDeg: 0.00,
    pitchDeg: 18.00,
    fovDeg: 62.0,
    nearM: 0.35,
    farM: 150.0,
    facing: 'west-north-west',
    stopKey: 'two_storeys_one_room',
    caption:
      'The section made legible: full-height pillars running past the ' +
      'mezzanine to the timber soffit. Without this the visitor never ' +
      'understands that the building is two storeys.',
  },
  {
    id: 'P4',
    title: 'Head of the stair',
    position: [8.000, 3.000, 4.200],
    headingDeg: 270.00,
    pitchDeg: 0.00,
    fovDeg: 62.0,
    nearM: 0.35,
    farM: 150.0,
    facing: 'south-south-west',
    stopKey: 'the_stair',
    caption:
      'Arrival on the upper floor; the gallery opens out.',
  },
  {
    id: 'P9',
    title: 'Zenana corner',
    position: [8.000, 17.500, 4.200],
    headingDeg: 223.30,
    pitchDeg: 0.00,
    fovDeg: 62.0,
    nearM: 0.35,
    farM: 150.0,
    facing: 'south-south-east',
    stopKey: 'the_small_room',
    caption:
      'Small, enclosed, private - the deliberate contrast with the ' +
      'hall.',
  },
  {
    id: 'P3',
    title: 'Museum room',
    position: [-15.000, 8.000, 1.600],
    headingDeg: 90.00,
    pitchDeg: 0.00,
    fovDeg: 62.0,
    nearM: 0.35,
    farM: 150.0,
    facing: 'north-north-east',
    stopKey: 'what_the_board_says',
    caption:
      'The enclosed end room; surviving painted plaster at close ' +
      'range.',
  },
  {
    id: 'P0',
    title: 'Front lawn',
    position: [0.000, -14.000, 0.900],
    headingDeg: 0.00,
    pitchDeg: 0.00,
    fovDeg: 62.0,
    nearM: 0.35,
    farM: 150.0,
    facing: 'west-north-west',
    stopKey: 'palace_overview',
    caption:
      'Orientation only. The visitor is already standing here in ' +
      'reality; the reconstruction teaches nothing they cannot see. ' +
      'Low priority, skippable.',
  },
];

/**
 * The palace legend is NOT the fort's. The fort's three tiers describe a
 * building drawn only as far as the evidence went - solid, ghosted, open-topped.
 * The palace still stands, so its form is confirmed and it is built whole. The
 * uncertainty here sits entirely in the paint.
 */
export const PALACE_LEGEND = [
  {
    key: 'form',
    label: 'The building',
    detail:
      'It still stands, so its form is confirmed. Sizes are derived from ' +
      'photographs and satellite imagery, not from any published plan.',
  },
  {
    key: 'colour',
    label: 'The paint',
    detail:
      'Two schemes, on two different surfaces. Inside, a madder-red ground ' +
      'with a white floral field. Outside, as Lt James Hunter painted it in ' +
      'February 1792: pale grounds, blue-green trellis, salmon-red arches.',
  },
  {
    key: 'unknown',
    label: 'What is not recorded',
    detail:
      'What was painted in each individual room. No source records it, so ' +
      'the pattern you see is the idiom, not the composition.',
  },
] as const;
